package fr.thomasschaller.todoserveur;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;
import java.util.ArrayList;
import java.util.Optional;

@RestController   // This means that this class is a Controller
@RequestMapping(path="/tasks") // This means URL's start with / (after Application path)
public class TaskController {


        @Autowired // This means to get the bean called TaskRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private TaskRepository taskRepository;
        @Autowired
    private AccountRepository accountRepository;

        @GetMapping(path="/add") // Map ONLY GET Requests
        public Task addTask(Principal principal, @RequestParam String title
                , @RequestParam String details) {
            // @ResponseBody means the returned Task is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            Account user =accountRepository.findByLogin(principal.getName());

            Task task = new Task();
            task.setTitle(title);
            task.setDescription(details);
            task.setAccount(user);
            taskRepository.save(task);
            return task;
        }

    @GetMapping(path="/{id}") // Map ONLY GET Requests with id defined
    public Task retrieveTask(@PathVariable Long id) {
        // @ResponseBody means the returned Task is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Optional<Task> n =taskRepository.findById(id);
            return n.orElse(null);

    }

    @PostMapping // Map ONLY POST Requests
    public Task addTask(Principal principal, @RequestBody Task task) {
        // @ResponseBody means the returned Task is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Account user =accountRepository.findByLogin(principal.getName());
        task.setAccount(user);
        taskRepository.save(task);
        return task;
    }

    @PutMapping // Map ONLY PUT Requests
    public Task updateTask( Principal principal,@RequestBody Task task) {
        // @ResponseBody means the returned Task is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Account user =accountRepository.findByLogin(principal.getName());
        task.setAccount(user);
        taskRepository.save(task);
        return task;
    }

    @DeleteMapping(path="/{id}") // Map ONLY DELETE Requests with id defined
    public Task deleteTask(@PathVariable Long id)
    {
            taskRepository.deleteById(id);
            Task t = new Task();
            t.setId(id);
            return t;

    }

        @GetMapping
        public Iterable<Task> getAllTasks(Principal principal) {
            // This returns a JSON or XML with the tasks
            Account user =accountRepository.findByLogin(principal.getName());
            if (user == null)
            {
                return new ArrayList<>();
            }
            return user.getTasks();
        }

        @GetMapping(path="/parent/{id}")
        public Iterable<Task> getTaskByParentId(@PathVariable Long id)
        {
            Optional<Task> t =taskRepository.findById(id);
            if (t.isPresent()){
                return taskRepository.findByParent(t.get());
            }
                else{
            return null;
        }
        }
}
