package fr.thomasschaller.todoserveur;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController   // This means that this class is a Controller
@RequestMapping(path="/todo") // This means URL's start with /todo (after Application path)
public class TodoController {


        @Autowired // This means to get the bean called TacheRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private TacheRepository tacheRepository;

        @GetMapping(path="/add") // Map ONLY GET Requests
        public @ResponseBody
        String addNewTache (@RequestParam String title
                , @RequestParam String details) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request

            Tache n = new Tache();
            n.setTitre(title);
            n.setDetails(details);
            tacheRepository.save(n);
            return "Saved";
        }

        @GetMapping(path="/all")
        public @ResponseBody Iterable<Tache> getAllTaches() {
            // This returns a JSON or XML with the users
            return tacheRepository.findAll();
        }
}
